[config]
# ...

[templates.hyprland]
input_path = '~/.config/matugen/templates/colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'


[templates.fuzzel]
input_path = '~/.config/matugen/templates/colors.ini'
output_path = '~/.config/fuzzel/colors.ini'
